import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import { useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { DeliveryAddress } from '@/features/customer/api';
import { confirmSheet } from '@/shared/components/ConfirmSheet';
import { haptics } from '@/shared/haptics';
import { colors, font, shadow } from '@/shared/theme';
import { Branch } from '@/shared/types';

export function ServiceSelect({ branches, addresses, authenticated, loading, error, onRetry, onLogin, onBrowseAsGuest, onManageAddresses, onChoosePickup, onChooseDelivery }: {
  branches: Branch[]; addresses: DeliveryAddress[]; authenticated: boolean; loading: boolean; error?: string;
  onRetry: () => void; onLogin: () => void; onBrowseAsGuest: () => void; onManageAddresses: () => void;
  onChoosePickup: (id: number) => void; onChooseDelivery: (address: DeliveryAddress) => void;
}) {
  const [mode, setMode] = useState<'delivery' | 'pickup'>('delivery');
  return <SafeAreaView style={s.serviceSafe} edges={['top','bottom']}><ScrollView bounces={false} showsVerticalScrollIndicator={false} contentContainerStyle={s.serviceScroll}>
    <LinearGradient colors={['#3B1611','#6E2E24']} style={s.serviceHero}>
      <View style={s.serviceBrandRow}><View style={s.serviceMark}><Ionicons name="pizza" size={24} color={colors.brown}/></View><Text style={s.serviceBrand}>PIZZA GETTO</Text><View style={s.serviceFresh}><View style={s.serviceFreshDot}/><Text style={s.serviceFreshText}>HECHO AL MOMENTO</Text></View></View>
      <Text style={s.serviceEyebrow}>EMPECEMOS TU ORDEN</Text><Text style={s.serviceTitle}>¿Cómo quieres{`\n`}tu pizza?</Text><Text style={s.serviceSubtitle}>Elige una opción. Te mostraremos precios, menú y disponibilidad correctos.</Text>
      <View style={s.servicePizzaArt}><View style={s.servicePizzaInner}><Ionicons name="pizza" size={68} color={colors.yellow}/></View></View>
    </LinearGradient>
    <View style={s.serviceBody}>
      <View style={s.serviceModes}>
        <Pressable accessibilityRole="tab" accessibilityState={{selected:mode==='delivery'}} onPress={()=>{haptics.select();setMode('delivery');}} style={[s.serviceMode,mode==='delivery'&&s.serviceModeActive]}><View style={[s.serviceModeIcon,mode==='delivery'&&s.serviceModeIconActive]}><Ionicons name="bicycle" size={23} color={mode==='delivery'?'white':colors.brown}/></View><View style={{flex:1}}><Text style={[s.serviceModeTitle,mode==='delivery'&&s.serviceModeTitleActive]}>Delivery</Text><Text style={s.serviceModeSub}>Lo llevamos a ti</Text></View>{mode==='delivery'&&<Ionicons name="checkmark-circle" size={21} color={colors.brown}/>}</Pressable>
        <Pressable accessibilityRole="tab" accessibilityState={{selected:mode==='pickup'}} onPress={()=>{haptics.select();setMode('pickup');}} style={[s.serviceMode,mode==='pickup'&&s.serviceModeActive]}><View style={[s.serviceModeIcon,mode==='pickup'&&s.serviceModeIconActive]}><Ionicons name="bag-handle" size={22} color={mode==='pickup'?'white':colors.brown}/></View><View style={{flex:1}}><Text style={[s.serviceModeTitle,mode==='pickup'&&s.serviceModeTitleActive]}>Recoger</Text><Text style={s.serviceModeSub}>En tu sucursal</Text></View>{mode==='pickup'&&<Ionicons name="checkmark-circle" size={21} color={colors.brown}/>}</Pressable>
      </View>
      {loading&&<View style={s.serviceLoading}><ActivityIndicator color={colors.brown}/><Text style={s.serviceLoadingText}>Buscando opciones disponibles…</Text></View>}
      {error&&<View style={s.serviceError}><Ionicons name="cloud-offline-outline" size={28} color={colors.red}/><Text style={s.setupTitle}>No pudimos conectar</Text><Text style={s.setupBody}>{error}</Text><Pressable style={s.servicePrimary} onPress={onRetry}><Text style={s.servicePrimaryText}>Intentar de nuevo</Text></Pressable></View>}
      {!loading&&!error&&mode==='delivery'&&(!authenticated?<View style={s.servicePanel}><View style={s.servicePanelIcon}><Ionicons name="location" size={26} color={colors.brown}/></View><Text style={s.servicePanelKicker}>DELIVERY PERSONALIZADO</Text><Text style={s.servicePanelTitle}>¿Dónde llevamos tu pizza?</Text><Text style={s.servicePanelCopy}>Inicia sesión para recuperar tus direcciones y confirmar cobertura automáticamente.</Text><Pressable onPress={onLogin} style={s.servicePrimary}><Text style={s.servicePrimaryText}>Continuar con mi dirección</Text><Ionicons name="arrow-forward" size={18} color="white"/></Pressable><Pressable onPress={onBrowseAsGuest} style={s.serviceGuest}><Text style={s.serviceGuestText}>Explorar el menú como invitado</Text></Pressable><View style={s.serviceTrust}><Ionicons name="shield-checkmark" size={16} color={colors.green}/><Text style={s.serviceTrustText}>Solo usamos tu ubicación para validar cobertura</Text></View></View>:<View><View style={s.serviceSectionHead}><View><Text style={s.serviceSectionKicker}>TUS DIRECCIONES</Text><Text style={s.serviceSectionTitle}>Elige dónde recibir</Text></View><Pressable onPress={onManageAddresses}><Text style={s.serviceEdit}>Administrar</Text></Pressable></View>{addresses.map(address=>{const available=Boolean(address.effective_location_id)&&address.delivery_open_now!==false;return <Pressable key={address.id} onPress={()=>onChooseDelivery(address)} style={[s.serviceOption,!available&&s.serviceOptionDisabled]}><View style={s.serviceOptionIcon}><Ionicons name={address.label==='Casa'?'home':'location'} size={21} color={colors.brown}/></View><View style={{flex:1}}><View style={s.serviceOptionTitleRow}><Text style={s.serviceOptionTitle}>{address.label}</Text>{address.is_default&&<View style={s.serviceDefault}><Text style={s.serviceDefaultText}>PRINCIPAL</Text></View>}</View><Text numberOfLines={2} style={s.serviceOptionAddress}>{address.street}</Text><View style={s.serviceStatusRow}><View style={[s.serviceStatusDot,{backgroundColor:available?colors.green:colors.red}]}/><Text style={[s.serviceStatusText,{color:available?colors.green:colors.red}]}>{!address.effective_location_id?'Ubicación por confirmar':address.delivery_open_now===false?`Cerrado · ${address.delivery_schedule_label||'Ver horario'}`:`Disponible · ${address.delivery_schedule_label||'Ahora'}`}</Text></View></View><Ionicons name="chevron-forward" size={20} color={colors.muted}/></Pressable>})}<Pressable onPress={onManageAddresses} style={s.serviceAdd}><View style={s.serviceAddIcon}><Ionicons name="add" size={22} color={colors.brown}/></View><View style={{flex:1}}><Text style={s.serviceAddTitle}>Agregar otra dirección</Text><Text style={s.serviceAddSub}>Ubícala con precisión en el mapa</Text></View><Ionicons name="map-outline" size={21} color={colors.brown}/></Pressable></View>)}
      {!loading&&!error&&mode==='pickup'&&<View><View style={s.serviceSectionHead}><View><Text style={s.serviceSectionKicker}>SUCURSALES</Text><Text style={s.serviceSectionTitle}>Recoge cerca de ti</Text></View><Text style={s.serviceCount}>{branches.filter(x=>x.pickup&&x.open).length} abiertas</Text></View>{branches.filter(item=>item.pickup).map(item=><Pressable key={item.id} style={[s.serviceOption,!item.open&&s.serviceOptionDisabled]} onPress={()=>{if(item.open){haptics.select();onChoosePickup(item.id);}else{haptics.warning();confirmSheet({title:'Sucursal cerrada',message:`Horario: ${item.scheduleLabel||'no disponible'}`,icon:'time',confirmText:'Entendido',cancelText:null});}}}><View style={s.serviceOptionIcon}><Ionicons name="storefront" size={21} color={colors.brown}/></View><View style={{flex:1}}><Text style={s.serviceOptionTitle}>{item.name.replace('Pizza Getto • ','')}</Text><Text numberOfLines={2} style={s.serviceOptionAddress}>{item.address}</Text><View style={s.serviceStatusRow}><View style={[s.serviceStatusDot,{backgroundColor:item.open?colors.green:colors.red}]}/><Text style={[s.serviceStatusText,{color:item.open?colors.green:colors.red}]}>{item.eta}</Text></View></View><Ionicons name="chevron-forward" size={20} color={colors.muted}/></Pressable>)}</View>}
      <View style={s.serviceFooter}><Ionicons name="lock-closed" size={13} color={colors.muted}/><Text style={s.serviceFooterText}>Puedes cambiar esta opción antes de confirmar tu pedido</Text></View>
    </View>
  </ScrollView></SafeAreaView>;
}

const s = StyleSheet.create({
  serviceSafe:{flex:1,backgroundColor:'#F8F3EE'},serviceScroll:{flexGrow:1,backgroundColor:'#F8F3EE'},
  serviceHero:{minHeight:330,paddingHorizontal:22,paddingTop:12,paddingBottom:54,overflow:'hidden'},
  serviceBrandRow:{flexDirection:'row',alignItems:'center',gap:9},serviceMark:{width:42,height:42,borderRadius:14,backgroundColor:colors.yellow,alignItems:'center',justifyContent:'center'},serviceBrand:{fontSize:19,fontFamily:font.display,letterSpacing:2.4,color:'white'},serviceFresh:{marginLeft:'auto',flexDirection:'row',alignItems:'center',gap:5,backgroundColor:'rgba(255,255,255,.1)',paddingHorizontal:9,paddingVertical:6,borderRadius:20},serviceFreshDot:{width:6,height:6,borderRadius:3,backgroundColor:colors.green},serviceFreshText:{fontSize: 10,fontFamily: font.black,letterSpacing:.7,color:'#F7E8E3'},
  serviceEyebrow:{fontSize:10,fontFamily: font.black,letterSpacing:1.8,color:colors.yellow,marginTop:40},serviceTitle:{fontSize:46,lineHeight:47,fontFamily:font.display,letterSpacing:.6,color:'white',marginTop:7,maxWidth:275},serviceSubtitle:{fontSize:12,lineHeight:18,color:'#DEC6BF',maxWidth:275,marginTop:10},
  servicePizzaArt:{position:'absolute',right:-48,bottom:-48,width:170,height:170,borderRadius:85,backgroundColor:'rgba(255,255,255,.06)',borderWidth:1,borderColor:'rgba(255,255,255,.1)',alignItems:'center',justifyContent:'center',transform:[{rotate:'12deg'}]},servicePizzaInner:{width:118,height:118,borderRadius:59,backgroundColor:'rgba(0,0,0,.12)',alignItems:'center',justifyContent:'center'},
  serviceBody:{marginTop:-28,borderTopLeftRadius:30,borderTopRightRadius:30,backgroundColor:'#F8F3EE',paddingHorizontal:18,paddingTop:18,paddingBottom:24,minHeight:480},
  serviceModes:{flexDirection:'row',gap:10,marginBottom:20},serviceMode:{flex:1,minHeight:86,borderRadius:19,backgroundColor:'white',borderWidth:1,borderColor:'#E9DED7',padding:12,flexDirection:'row',alignItems:'center',gap:10,...shadow},serviceModeActive:{backgroundColor:colors.yellowSoft,borderColor:colors.yellow},serviceModeIcon:{width:42,height:42,borderRadius:14,backgroundColor:'#F4EAE4',alignItems:'center',justifyContent:'center'},serviceModeIconActive:{backgroundColor:colors.brown},serviceModeTitle:{fontSize:14,fontFamily: font.black,color:colors.text},serviceModeTitleActive:{color:colors.brown},serviceModeSub:{fontSize: 10,color:colors.muted,marginTop:2},
  serviceLoading:{paddingVertical:54,alignItems:'center',gap:13},serviceLoadingText:{fontSize:12,color:colors.muted,fontFamily: font.bold},serviceError:{backgroundColor:'white',borderRadius:22,padding:24,alignItems:'center',borderWidth:1,borderColor:colors.border},
  setupTitle: { color: colors.text, fontSize: 18, fontFamily: font.black, marginTop: 10 },
  setupBody: { color: colors.muted, fontSize: 12, textAlign: 'center', marginTop: 5 },
  servicePanel:{backgroundColor:'white',borderRadius:24,padding:22,alignItems:'center',borderWidth:1,borderColor:'#E9DED7',...shadow},servicePanelIcon:{width:58,height:58,borderRadius:20,backgroundColor:colors.yellowSoft,alignItems:'center',justifyContent:'center'},servicePanelKicker:{fontSize: 10,fontFamily: font.black,letterSpacing:1.2,color:colors.orange,marginTop:17},servicePanelTitle:{fontSize:27,lineHeight:29,fontFamily:font.display,letterSpacing:.4,color:colors.text,textAlign:'center',marginTop:5},servicePanelCopy:{fontSize:12,lineHeight:18,color:colors.muted,textAlign:'center',marginTop:8,maxWidth:290},servicePrimary:{height:54,borderRadius:16,backgroundColor:colors.brown,alignSelf:'stretch',marginTop:20,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:9},servicePrimaryText:{fontSize:14,fontFamily: font.black,color:'white'},serviceGuest:{paddingVertical:15,alignSelf:'stretch',alignItems:'center'},serviceGuestText:{fontSize:12,fontFamily: font.black,color:colors.brown,textDecorationLine:'underline'},serviceTrust:{flexDirection:'row',alignItems:'center',gap:6,backgroundColor:'#EDF8F0',paddingHorizontal:11,paddingVertical:8,borderRadius:12},serviceTrustText:{fontSize: 10,fontFamily: font.bold,color:'#3E7250'},
  serviceSectionHead:{flexDirection:'row',alignItems:'flex-end',justifyContent:'space-between',marginBottom:12,paddingHorizontal:2},serviceSectionKicker:{fontSize: 10,fontFamily: font.black,letterSpacing:1.3,color:colors.orange},serviceSectionTitle:{fontSize:25,fontFamily:font.display,letterSpacing:.4,color:colors.text,marginTop:3},serviceEdit:{fontSize:11,fontFamily: font.black,color:colors.brown,textDecorationLine:'underline'},serviceCount:{fontSize:10,fontFamily: font.extraBold,color:colors.green,backgroundColor:'#E6F5EB',paddingHorizontal:10,paddingVertical:6,borderRadius:12},
  serviceOption:{backgroundColor:'white',borderRadius:19,borderWidth:1,borderColor:'#E9DED7',padding:14,flexDirection:'row',alignItems:'center',gap:12,marginBottom:10},serviceOptionDisabled:{opacity:.58,backgroundColor:'#F5F1EE'},serviceOptionIcon:{width:46,height:46,borderRadius:15,backgroundColor:colors.yellowSoft,alignItems:'center',justifyContent:'center'},serviceOptionTitleRow:{flexDirection:'row',alignItems:'center',gap:7},serviceOptionTitle:{fontSize:14,fontFamily: font.black,color:colors.text},serviceDefault:{backgroundColor:colors.brown,borderRadius:7,paddingHorizontal:6,paddingVertical:3},serviceDefaultText:{fontSize: 10,fontFamily: font.black,letterSpacing:.7,color:'white'},serviceOptionAddress:{fontSize:10,lineHeight:14,color:colors.muted,marginTop:3},serviceStatusRow:{flexDirection:'row',alignItems:'center',gap:5,marginTop:6},serviceStatusDot:{width:6,height:6,borderRadius:3},serviceStatusText:{fontSize: 10,fontFamily: font.black},
  serviceAdd:{borderRadius:19,borderWidth:1.5,borderStyle:'dashed',borderColor:'#CBB7AC',padding:14,flexDirection:'row',alignItems:'center',gap:12,marginTop:4},serviceAddIcon:{width:42,height:42,borderRadius:14,backgroundColor:colors.yellow,alignItems:'center',justifyContent:'center'},serviceAddTitle:{fontSize:13,fontFamily: font.black,color:colors.brown},serviceAddSub:{fontSize: 10,color:colors.muted,marginTop:2},serviceFooter:{flexDirection:'row',alignItems:'center',justifyContent:'center',gap:5,marginTop:20},serviceFooterText:{fontSize: 10,color:colors.muted},
});
